# runs on pull requests, manually, and the main branch
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  env:
    GIT_COMMITTER_NAME: muath
    GIT_COMMITTER_EMAIL: muathye@gmail.com
  my_job:
    name: push details to Dev.to
    permissions:
      contents: write # this lets the bot update the post in github
    runs-on: ubuntu-latest # ubuntu costs half the price of windows

    steps:
    - uses: actions/checkout@v3 # checks out my code to the actions build
    - name: Publish articles on Dev.to
      uses: sinedied/publish-devto@v2
      with:
        devto_key: ${{ secrets.SECRET_DEVTO_TOKEN }} # the secret you setup
        github_token: ${{ secrets.GITHUB_TOKEN }} # this is an inbuilt secret by github
        files: 'markdown/**/*.md'
        branch: father
        conventional_commits: true
        dry_run: false # set this to true if you want to do a dry run

# Rename the local branch if you renamed the remote branch on github.
# git branch -m father father
# git fetch origin
# git branch -u origin/father father
# git remote set-head origin -a
